# [global]
# progress_full_character = "="
# progress_empty_character = "="
# progress_prefix = "["
# progress_suffix = "]"
# time_format = "%Y-%m-%d %H:%M:%S"

# [banner]
# color = "red"
# command = "hostname | figlet -f slant"
# if you don't want a dependency on figlet, you can generate your
# banner however you want, put it in a file, and then use something like:
# command = "cat banner.txt"

# [weather]
# url = "https://wttr.in/New+York,New+York?0"
# user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
# proxy = "http://proxy:8080"

# [service_status]
# Accounts = "accounts-daemon"
# Cron = "cron"

# [docker]
#    [docker.containers]
#    "nextcloud-nextcloud-1" = "Nextcloud"
#    "nextcloud-mariadb-1" = "Nextcloud Database"
#
#    [docker.composes]
#    "nextcloud" = "Nextcloud"

# [uptime]
# prefix = "Up"

# [user_service_status]
# gpg-agent = "gpg-agent"

# [ssl_certificates]
# sort_method = "manual"
#
#    [ssl_certificates.certs]
#    CertName1 = "/path/to/cert1.pem"
#    CertName2 = "/path/to/cert2.pem"

# [filesystems]
# root = "/"

# [memory]
# swap_pos = "beside" # or "below" or "none"

# [fail_2_ban]
# jails = ["sshd", "anotherjail"]

# [last_login]
# sally = 2
# jimmy = 1

# [last_run]

